# this works as well and is the smallest.
FROM ubuntu:23.04
ENV DEBIAN_FRONTEND=noninteractive

# Setup
RUN apt update && \
    apt install -y --no-install-recommends bash \
                #    build-essential \
                   curl \
                   ca-certificates \
                   python3 \
                   python3-pip && \
                   apt autoremove -y && \
                   apt purge -y --auto-remove && \  
                   rm -rf /var/lib/apt/lists/*
 
# Your stuff
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    pip3 install uvicorn[standard] fastapi && \
    pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# EXPOSE 8000